version: '3.8'

services:
  web:
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    volumes:
      - ./:/app
    environment:
      - DEBUG=1
  
  worker:
    command: celery -A config worker --loglevel=info
    volumes:
      - ./:/app
    environment:
      - DEBUG=1

  beat:
    command: celery -A config beat --loglevel=info
    volumes:
      - ./:/app
    environment:
      - DEBUG=1
