version: '3.8'

services:
  web:
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8001:8000'
    volumes:
      - ./:/app
    env_file: .env
    environment:
      - DEBUG=1
  
  worker:
    command: celery -A config.settings.celery:app worker --loglevel=info
    volumes:
      - ./:/app
    env_file: .env
    environment:
      - DEBUG=1

  beat:
    command: celery -A config.settings.celery:app beat --loglevel=info
    volumes:
      - ./:/app
    env_file: .env
    environment:
      - DEBUG=1

  db:
    image: postgres:15-alpine
    ports:
      - '5433:5432'
    env_file: .env

  redis:
    image: redis:7-alpine
    ports:
      - '6380:6379'
